"""Tests for cli.py - command-line interface."""

import subprocess
import sys
from pathlib import Path

import pytest


@pytest.fixture
def valid_config(tmp_path):
    """Create a valid minimal config file."""
    config = tmp_path / "config.yaml"
    config.write_text(
        """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
"""
    )
    return config


@pytest.fixture
def config_with_module(tmp_path):
    """Create a config with build.module for go.mod generation."""
    config = tmp_path / "config.yaml"
    config.write_text(
        """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
build:
  module: github.com/test/checker
  go_version: "1.23"
"""
    )
    return config


def run_cli(*args: str) -> subprocess.CompletedProcess:
    """Run pytrekgen CLI with given arguments."""
    return subprocess.run(
        [sys.executable, "-m", "pytrekgen.cli", *args],
        capture_output=True,
        text=True,
    )


class TestCliBasics:
    """Basic CLI functionality tests."""

    def test_missing_input_flag(self):
        result = run_cli()
        assert result.returncode != 0
        assert "required" in result.stderr.lower() or "error" in result.stderr.lower()

    def test_nonexistent_input_file(self, tmp_path):
        result = run_cli("-i", str(tmp_path / "missing.yaml"))
        assert result.returncode != 0
        assert "not found" in result.stderr.lower()

    def test_version_flag(self):
        result = run_cli("--version")
        assert result.returncode == 0
        assert "pytrekgen" in result.stdout.lower()

    def test_help_flag(self):
        result = run_cli("--help")
        assert result.returncode == 0
        assert "usage" in result.stdout.lower() or "-i" in result.stdout


class TestStdoutOutput:
    """Tests for stdout output mode."""

    def test_outputs_to_stdout(self, valid_config):
        result = run_cli("-i", str(valid_config))
        assert result.returncode == 0
        assert "package main" in result.stdout
        assert "func main()" in result.stdout

    def test_includes_header_comment(self, valid_config):
        result = run_cli("-i", str(valid_config))
        assert result.returncode == 0
        assert "Code generated by pytrekgen" in result.stdout


class TestFileOutput:
    """Tests for file output mode."""

    def test_writes_to_file(self, valid_config, tmp_path):
        output = tmp_path / "main.go"
        result = run_cli("-i", str(valid_config), "-o", str(output))
        assert result.returncode == 0
        assert output.exists()
        content = output.read_text()
        assert "package main" in content

    def test_creates_parent_directories(self, valid_config, tmp_path):
        output = tmp_path / "nested" / "dir" / "main.go"
        result = run_cli("-i", str(valid_config), "-o", str(output))
        assert result.returncode == 0
        assert output.exists()

    def test_logs_generated_file(self, valid_config, tmp_path):
        output = tmp_path / "main.go"
        result = run_cli("-i", str(valid_config), "-o", str(output))
        assert result.returncode == 0
        assert "Generated" in result.stderr or "main.go" in result.stderr


class TestWithGomod:
    """Tests for --with-gomod flag."""

    def test_requires_output_flag(self, config_with_module):
        result = run_cli("-i", str(config_with_module), "--with-gomod")
        assert result.returncode != 0
        assert "requires" in result.stderr.lower() and "-o" in result.stderr

    def test_requires_build_module(self, valid_config, tmp_path):
        output = tmp_path / "out" / "main.go"
        result = run_cli("-i", str(valid_config), "-o", str(output), "--with-gomod")
        assert result.returncode != 0
        assert "build.module" in result.stderr.lower()

    def test_generates_gomod(self, config_with_module, tmp_path):
        output = tmp_path / "out" / "main.go"
        result = run_cli("-i", str(config_with_module), "-o", str(output), "--with-gomod")
        assert result.returncode == 0

        gomod = tmp_path / "out" / "go.mod"
        assert gomod.exists()
        content = gomod.read_text()
        assert "module github.com/test/checker" in content
        assert "go 1.23" in content

    def test_logs_gomod_generation(self, config_with_module, tmp_path):
        output = tmp_path / "out" / "main.go"
        result = run_cli("-i", str(config_with_module), "-o", str(output), "--with-gomod")
        assert result.returncode == 0
        assert "go.mod" in result.stderr


class TestDebugFlag:
    """Tests for --debug flag."""

    def test_debug_enables_verbose_logging(self, valid_config, tmp_path):
        output = tmp_path / "main.go"
        result = run_cli("-i", str(valid_config), "-o", str(output), "--debug")
        assert result.returncode == 0
        # Debug mode should show loading messages
        assert "Loading" in result.stderr or "DEBUG" in result.stderr or "Loaded" in result.stderr


class TestCustomTemplateDir:
    """Tests for -t/--templates flag."""

    def test_nonexistent_template_dir(self, valid_config, tmp_path):
        result = run_cli(
            "-i", str(valid_config), "-t", str(tmp_path / "nonexistent")
        )
        assert result.returncode != 0
        assert "not found" in result.stderr.lower()

    def test_custom_template_dir(self, valid_config, tmp_path):
        # Create a custom template
        template_dir = tmp_path / "templates"
        template_dir.mkdir()
        (template_dir / "base.go.j2").write_text(
            """// Custom template
package main

func main() {
    // Custom: {{ config.lab.name }}
}
"""
        )

        result = run_cli("-i", str(valid_config), "-t", str(template_dir))
        assert result.returncode == 0
        assert "// Custom template" in result.stdout
        assert "Custom: Test" in result.stdout


class TestErrorHandling:
    """Tests for error handling."""

    def test_invalid_yaml(self, tmp_path):
        config = tmp_path / "invalid.yaml"
        config.write_text("this is not valid yaml: [")
        result = run_cli("-i", str(config))
        assert result.returncode != 0
        assert "error" in result.stderr.lower() or "failed" in result.stderr.lower()

    def test_missing_required_field(self, tmp_path):
        config = tmp_path / "incomplete.yaml"
        config.write_text(
            """
lab:
  id: "01"
  # missing name and env_prefix
"""
        )
        result = run_cli("-i", str(config))
        assert result.returncode != 0

    def test_unknown_check_type(self, tmp_path):
        config = tmp_path / "bad_check.yaml"
        config.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
checks:
  - type: nonexistent_check_type
    foo: bar
"""
        )
        result = run_cli("-i", str(config))
        assert result.returncode != 0
