"""Integration tests - verify generated code compiles."""

import shutil
import subprocess
from pathlib import Path

import pytest

from pytrekgen.generator import Generator


EXAMPLES_DIR = Path(__file__).parent.parent / "examples"


@pytest.fixture
def generator():
    return Generator()


def has_go():
    """Check if Go is available."""
    return shutil.which("go") is not None


class TestExamplesGenerate:
    """All example YAML files should generate valid code."""

    @pytest.mark.parametrize(
        "yaml_file",
        list(EXAMPLES_DIR.glob("*.yaml")),
        ids=lambda p: p.name,
    )
    def test_example_generates(self, generator, yaml_file):
        config = generator.load_config(yaml_file)
        code = generator.generate(config, source_file=yaml_file.name)

        assert "package main" in code
        assert "func main()" in code
        assert "// Code generated by pytrekgen" in code


class TestExamplesHaveExpectedContent:
    """Examples should have expected structure based on their checks."""

    def test_lab00_minimal(self, generator):
        """lab00 is a minimal example."""
        yaml_file = EXAMPLES_DIR / "lab00.yaml"
        if not yaml_file.exists():
            pytest.skip("lab00.yaml not found")

        config = generator.load_config(yaml_file)
        code = generator.generate(config)

        assert "package main" in code

    def test_lab02_has_kafka_and_postgres(self, generator):
        """lab02 uses Kafka and PostgreSQL."""
        yaml_file = EXAMPLES_DIR / "lab02.yaml"
        if not yaml_file.exists():
            pytest.skip("lab02.yaml not found")

        config = generator.load_config(yaml_file)
        code = generator.generate(config)

        assert "github.com/segmentio/kafka-go" in code
        assert "github.com/lib/pq" in code
        assert "checkKafkaTopicExists" in code

    def test_lab03_has_roundtrip(self, generator):
        """lab03 uses kafka_roundtrip."""
        yaml_file = EXAMPLES_DIR / "lab03.yaml"
        if not yaml_file.exists():
            pytest.skip("lab03.yaml not found")

        config = generator.load_config(yaml_file)
        code = generator.generate(config)

        assert "kafkaRoundtrip" in code
        assert "checkForbiddenAddress" in code


@pytest.mark.skipif(not has_go(), reason="Go not installed")
class TestGeneratedCodeCompiles:
    """Generated Go code should compile (requires Go installed)."""

    @pytest.mark.parametrize(
        "yaml_file",
        list(EXAMPLES_DIR.glob("*.yaml")),
        ids=lambda p: p.name,
    )
    def test_code_compiles(self, generator, yaml_file, tmp_path):
        config = generator.load_config(yaml_file)
        code = generator.generate(config)

        # Write generated code
        go_file = tmp_path / "main.go"
        go_file.write_text(code)

        # Generate go.mod if we have module info
        if config.build.module:
            gomod = tmp_path / "go.mod"
            gomod.write_text(generator.generate_gomod(config))

            # Run go mod tidy
            result = subprocess.run(
                ["go", "mod", "tidy"],
                cwd=tmp_path,
                capture_output=True,
                timeout=120,
            )
            assert result.returncode == 0, f"go mod tidy failed:\n{result.stderr.decode()}"

            # Run go build
            result = subprocess.run(
                ["go", "build", "-o", "checker", "."],
                cwd=tmp_path,
                capture_output=True,
                timeout=120,
            )
            assert result.returncode == 0, f"go build failed:\n{result.stderr.decode()}"

    def test_minimal_config_compiles(self, generator, tmp_path):
        """A minimal config should generate compilable code."""
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)

        go_file = tmp_path / "main.go"
        go_file.write_text(code)

        gomod = tmp_path / "go.mod"
        gomod.write_text(generator.generate_gomod(config))

        # go mod tidy
        result = subprocess.run(
            ["go", "mod", "tidy"],
            cwd=tmp_path,
            capture_output=True,
            timeout=120,
        )
        assert result.returncode == 0, f"go mod tidy failed:\n{result.stderr.decode()}"

        # go build
        result = subprocess.run(
            ["go", "build", "-o", "checker", "."],
            cwd=tmp_path,
            capture_output=True,
            timeout=120,
        )
        assert result.returncode == 0, f"go build failed:\n{result.stderr.decode()}"


@pytest.mark.skipif(not has_go(), reason="Go not installed")
class TestGoVet:
    """Generated code should pass go vet."""

    @pytest.mark.parametrize(
        "yaml_file",
        list(EXAMPLES_DIR.glob("*.yaml")),
        ids=lambda p: p.name,
    )
    def test_go_vet_passes(self, generator, yaml_file, tmp_path):
        config = generator.load_config(yaml_file)
        code = generator.generate(config)

        go_file = tmp_path / "main.go"
        go_file.write_text(code)

        if config.build.module:
            gomod = tmp_path / "go.mod"
            gomod.write_text(generator.generate_gomod(config))

            # Need to run go mod tidy first for vet to work
            subprocess.run(
                ["go", "mod", "tidy"],
                cwd=tmp_path,
                capture_output=True,
                timeout=120,
            )

            result = subprocess.run(
                ["go", "vet", "./..."],
                cwd=tmp_path,
                capture_output=True,
                timeout=60,
            )
            assert result.returncode == 0, f"go vet failed:\n{result.stderr.decode()}"


class TestCodeStructure:
    """Tests for generated code structure."""

    def test_has_setup_usage(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)
        assert "func setupUsage()" in code

    def test_has_confirm_settings(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)
        assert "func confirmSettings()" in code

    def test_has_tracker_variable(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)
        assert "var tracker analytics.Tracker" in code

    def test_calls_ping_start_and_finish(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)
        assert "tracker.PingStart()" in code
        assert "tracker.PingFinish()" in code

    def test_loads_env(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        code = generator.generate(config)
        assert "env.LoadEnv()" in code

    def test_prints_success_message(self, generator):
        from conftest import minimal_config

        config = minimal_config()
        config.success_message = "All done!"
        code = generator.generate(config)
        assert "All done!" in code


class TestRoundtripConsistency:
    """Test that multiple generations produce the same output."""

    def test_deterministic_output(self, generator):
        """Generating the same config twice should produce identical output."""
        from conftest import minimal_config

        config = minimal_config(
            checks=[
                {"type": "http_get", "url": "http://localhost:8080"},
                {
                    "type": "kafka_topic_exists",
                    "kafka_addr_env": "K",
                    "kafka_topic_env": "T",
                },
            ]
        )

        code1 = generator.generate(config, source_file="test.yaml")
        code2 = generator.generate(config, source_file="test.yaml")

        assert code1 == code2
