"""Tests for generator.py - code generation logic."""

import pytest
from pathlib import Path

from pytrekgen.generator import Generator
from pytrekgen.config import LabConfig, ConfirmField

from conftest import minimal_config


class TestGeneratorInit:
    """Tests for Generator initialization."""

    def test_default_template_dir(self):
        gen = Generator()
        assert gen.env is not None

    def test_custom_template_dir(self, tmp_path):
        # Create a minimal template
        template = tmp_path / "base.go.j2"
        template.write_text("package main\n")

        gen = Generator(template_dir=tmp_path)
        assert gen.env is not None


class TestLoadConfig:
    """Tests for Generator.load_config()."""

    def test_load_minimal_yaml(self, generator, tmp_path):
        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
"""
        )
        config = generator.load_config(config_file)
        assert config.lab.id == "01"
        assert config.lab.name == "Test"
        assert config.lab.env_prefix == "TEST"

    def test_load_with_checks(self, generator, tmp_path):
        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
checks:
  - type: http_get
    url: "http://localhost:8080"
"""
        )
        config = generator.load_config(config_file)
        assert len(config.checks) == 1
        assert config.checks[0].type == "http_get"

    def test_load_with_code_file(self, generator, tmp_path):
        code_file = tmp_path / "custom.go"
        code_file.write_text("func myFunc() { return nil }")

        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
custom_code:
  code_file: custom.go
"""
        )
        config = generator.load_config(config_file)
        assert "func myFunc()" in config.custom_code.code

    def test_load_with_types_file(self, generator, tmp_path):
        types_file = tmp_path / "types.go"
        types_file.write_text("type MyStruct struct { Name string }")

        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
custom_code:
  types_file: types.go
"""
        )
        config = generator.load_config(config_file)
        assert "type MyStruct struct" in config.custom_code.types

    def test_load_merges_file_and_inline_code(self, generator, tmp_path):
        code_file = tmp_path / "custom.go"
        code_file.write_text("func fromFile() {}")

        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
custom_code:
  code_file: custom.go
  code: |
    func fromInline() {}
"""
        )
        config = generator.load_config(config_file)
        assert "func fromFile()" in config.custom_code.code
        assert "func fromInline()" in config.custom_code.code

    def test_confirm_display_normalization_strings(self, generator, tmp_path):
        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
confirm_display:
  - STUDENT
  - KAFKA_ADDR
"""
        )
        config = generator.load_config(config_file)
        fields = config.get_confirm_fields()
        assert len(fields) == 2
        assert fields[0].name == "STUDENT"
        assert fields[0].masked is False

    def test_confirm_display_normalization_mixed(self, generator, tmp_path):
        config_file = tmp_path / "test.yaml"
        config_file.write_text(
            """
lab:
  id: "01"
  name: "Test"
  env_prefix: "TEST"
confirm_display:
  - STUDENT
  - name: TOKEN
    masked: true
"""
        )
        config = generator.load_config(config_file)
        fields = config.get_confirm_fields()
        assert fields[0].name == "STUDENT"
        assert fields[0].masked is False
        assert fields[1].name == "TOKEN"
        assert fields[1].masked is True


class TestGenerate:
    """Tests for Generator.generate()."""

    def test_generates_package_main(self, generator):
        config = minimal_config()
        code = generator.generate(config)
        assert "package main" in code

    def test_generates_func_main(self, generator):
        config = minimal_config()
        code = generator.generate(config)
        assert "func main()" in code

    def test_includes_header_comment(self, generator):
        config = minimal_config()
        code = generator.generate(config)
        assert "// Code generated by pytrekgen" in code

    def test_includes_source_file_comment(self, generator):
        config = minimal_config()
        code = generator.generate(config, source_file="lab01.yaml")
        assert "// Source: lab01.yaml" in code

    def test_env_prefix_substituted_in_usage(self, generator):
        config = minimal_config()
        config.usage_header = "${ENV_PREFIX}_FOO is required"
        code = generator.generate(config)
        assert "TEST_FOO is required" in code
        assert "${ENV_PREFIX}" not in code

    def test_includes_success_message(self, generator):
        config = minimal_config()
        config.success_message = "All tests passed!"
        code = generator.generate(config)
        assert "All tests passed!" in code

    def test_includes_required_env(self, generator):
        config = minimal_config(
            required_env=[{"name": "TOKEN", "error": "Need token"}]
        )
        code = generator.generate(config)
        assert '"TEST_TOKEN"' in code
        assert '"Need token"' in code

    def test_includes_env_one_of_validation(self, generator):
        config = minimal_config(
            env_one_of=[{"vars": ["REDIS", "REDIS_URL"], "error": "Need one redis env"}]
        )
        code = generator.generate(config)
        assert '"TEST_REDIS"' in code
        assert '"TEST_REDIS_URL"' in code
        assert "Need one redis env" in code
        assert "strings.TrimSpace" in code

    def test_includes_custom_code(self, generator):
        config = minimal_config()
        config.custom_code.code = "func myCustomFunc() error { return nil }"
        code = generator.generate(config)
        assert "func myCustomFunc()" in code

    def test_includes_custom_imports(self, generator):
        config = minimal_config()
        config.custom_code.imports = ["encoding/json", "time"]
        code = generator.generate(config)
        assert '"encoding/json"' in code
        assert '"time"' in code

    def test_trekker_import_shorthand(self, generator):
        config = minimal_config()
        config.custom_code.imports = ["trekker:utils"]
        code = generator.generate(config)
        assert '"github.com/shrimpsizemoose/trekker/utils"' in code


class TestConditionalImports:
    """Test that imports are only included when needed."""

    def test_no_kafka_import_without_kafka_checks(self, generator):
        config = minimal_config(checks=[])
        code = generator.generate(config)
        assert "kafka-go" not in code
        assert "github.com/segmentio/kafka-go" not in code

    def test_has_kafka_import_with_topic_check(self, generator):
        config = minimal_config(
            checks=[
                {"type": "kafka_topic_exists", "kafka_addr_env": "K", "kafka_topic_env": "T"}
            ]
        )
        code = generator.generate(config)
        assert "github.com/segmentio/kafka-go" in code

    def test_has_kafka_import_with_roundtrip_check(self, generator):
        config = minimal_config(
            checks=[
                {"type": "kafka_roundtrip", "kafka_addr_env": "K", "kafka_topic_env": "T"}
            ]
        )
        code = generator.generate(config)
        assert "github.com/segmentio/kafka-go" in code

    def test_no_postgres_import_without_postgres_checks(self, generator):
        config = minimal_config(checks=[])
        code = generator.generate(config)
        assert "lib/pq" not in code

    def test_has_postgres_import_with_connect_check(self, generator):
        config = minimal_config(
            checks=[{"type": "postgres_connect", "postgres_url_env": "DB"}]
        )
        code = generator.generate(config)
        assert "github.com/lib/pq" in code

    def test_no_context_without_context_checks(self, generator):
        config = minimal_config(checks=[])
        code = generator.generate(config)
        assert "rootCtx" not in code
        assert "signal.NotifyContext" not in code

    def test_has_context_with_http_check(self, generator):
        config = minimal_config(
            checks=[{"type": "http_get", "url": "http://localhost"}]
        )
        code = generator.generate(config)
        assert "rootCtx" in code
        assert "signal.NotifyContext" in code

    def test_has_flag_import_always(self, generator):
        config = minimal_config(flags=[])
        code = generator.generate(config)
        # flag is always imported for built-in --ping/--version/--checks flags
        assert '"flag"' in code
        assert "flag.Parse()" in code

    def test_has_flag_import_with_flags(self, generator):
        config = minimal_config(flags=[{"name": "debug", "type": "bool"}])
        code = generator.generate(config)
        assert '"flag"' in code
        assert "flag.Parse()" in code

    def test_no_strings_import_without_string_checks(self, generator):
        config = minimal_config(checks=[])
        code = generator.generate(config)
        # strings is used by forbidden_address and param_equals
        assert '"strings"' not in code

    def test_has_strings_import_with_forbidden_address(self, generator):
        config = minimal_config(
            checks=[{"type": "forbidden_address", "env_var": "X", "forbidden": ["y"]}]
        )
        code = generator.generate(config)
        assert '"strings"' in code

    def test_has_utils_import_with_masked_fields(self, generator):
        config = minimal_config()
        config.confirm_display = [ConfirmField(name="TOKEN", masked=True)]
        code = generator.generate(config)
        assert "trekker/utils" in code
        assert "utils.MaskToken" in code


class TestGenerateGoMod:
    """Tests for Generator.generate_gomod()."""

    def test_generates_module_line(self, generator):
        config = minimal_config()
        config.build.module = "github.com/example/checker"
        gomod = generator.generate_gomod(config)
        assert "module github.com/example/checker" in gomod

    def test_generates_go_version(self, generator):
        config = minimal_config()
        config.build.module = "github.com/example/checker"
        config.build.go_version = "1.22"
        gomod = generator.generate_gomod(config)
        assert "go 1.22" in gomod

    def test_raises_without_module(self, generator):
        config = minimal_config()
        config.build.module = ""
        with pytest.raises(ValueError, match="module is required"):
            generator.generate_gomod(config)

    def test_ends_with_newline(self, generator):
        config = minimal_config()
        config.build.module = "github.com/example/checker"
        gomod = generator.generate_gomod(config)
        assert gomod.endswith("\n")


class TestGenerateToFile:
    """Tests for Generator.generate_to_file()."""

    def test_writes_to_file(self, generator, tmp_path):
        config = minimal_config()
        output = tmp_path / "main.go"
        generator.generate_to_file(config, output)
        assert output.exists()
        content = output.read_text()
        assert "package main" in content

    def test_creates_parent_directories(self, generator, tmp_path):
        config = minimal_config()
        output = tmp_path / "nested" / "dir" / "main.go"
        generator.generate_to_file(config, output)
        assert output.exists()

    def test_includes_source_file(self, generator, tmp_path):
        config = minimal_config()
        output = tmp_path / "main.go"
        generator.generate_to_file(config, output, source_file="config.yaml")
        content = output.read_text()
        assert "// Source: config.yaml" in content


class TestGenerateGoModToFile:
    """Tests for Generator.generate_gomod_to_file()."""

    def test_writes_gomod(self, generator, tmp_path):
        config = minimal_config()
        config.build.module = "github.com/example/checker"
        generator.generate_gomod_to_file(config, tmp_path)
        gomod = tmp_path / "go.mod"
        assert gomod.exists()
        content = gomod.read_text()
        assert "module github.com/example/checker" in content

    def test_creates_parent_directories(self, generator, tmp_path):
        config = minimal_config()
        config.build.module = "github.com/example/checker"
        output_dir = tmp_path / "nested" / "dir"
        generator.generate_gomod_to_file(config, output_dir)
        assert (output_dir / "go.mod").exists()
